server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.mjs$ {
        default_type application/javascript;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' '*';
    }

    location / {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Allow-Headers' '*';
        try_files $uri $uri/ /index.html;
    }
}
